### ISSUE TITLE
Sort/Alpha Title is not working ?

### ISSUE THREAD

**Issue by ReyVGM** [pascl/pbPSCReAlpha#21]
Hello.

I have the latest version of pbPSCReAlpha (1.3), I'm using bleemsync 1.1, a Micro SD with USB card reader (no OTG), and I'm also using the stock UI (the carousel).

I use the Alpha Title option in pbPSCReAlpha so that I can reorder games how I want. After making all the changes in pbPSCReAlpha, I hit "recreate database" and everything went through fine. But when I boot the PS Classic, all games are still sorted by the title name and not the alpha one.

Is the Alpha Title option not compatible with the stock UI, or did I do something wrong?
I had used the BleemsyncUI.com beforehand to sort the games, but I was told by one of the devs that the sort option in the website is actually not working. Maybe that caused some compatibility issues with pbPSCReAlpha?

**Comment by pascl** [comment]
In bleemsync options (L1 on boot, bleemsyncui, or direct edition of bleemsync_cfg.ini), you need to disable the alphabeticalize option (don't remember the exact wording) to let the sorting as it is in ReAlpha.

**Comment by ReyVGM** [comment]
Thanks. I'll try that!

**Comment by pascl** [comment]
Just a precision:
If you have the stock games displayed, they will appear before your custom games, they won't be mixed alphabetically with the custom ones.

**Comment by ReyVGM** [comment]
That's fine, no problem. Thanks for the info.

**Comment by ReyVGM** [comment]
Worked like a charm, thanks a lot! I've asked in so many places and finally someone provided the answer :)

I don't know if this is in the FAQ (I was at work so I didn't read it completely), but if it isn't, you might want to add it for the other people that are wondering the same thing.

The option in bleemsync is called "Link Alphabeticalise" and it needs to be False for the sort names to work.
