### ISSUE TITLE
Getting errors when the information is correct..

### ISSUE THREAD

**Issue by jhaleit** [pascl/pbPSCReAlpha#24]
![Screen Shot 2019-06-12 at 10 34 46 PM](https://user-images.githubusercontent.com/4206603/59399622-aec57b80-8d62-11e9-8eea-1468468d6262.png)

I don't know what's going on. The errors doesn't seem correct either..

I'm using Bleemsync 1.1.0

**Comment by pascl** [comment]
You have mixed mods somewhere. Autobleem creates folders with game names, bleemsync only wants numbered folders (error 1).

The pcsx.cfg file warning doesn't matter here.

The discs information in game.ini is supposed to have the filename without the extension (error 3 and 5).

(Error 4) Special characters can do some strange behaviour (picture not displaying, game not starting, saves not saving, ...) on the psc, so I don't recommend to use some (the '!' here).
