### ISSUE TITLE
Add support for CHD files?

### ISSUE THREAD

**Issue by AnotherLife** [pascl/pbPSCReAlpha#26]
Since now pcsx rearmed supports CHD?

**Comment by MessiahMozgus** [comment]
This would be nice.

**Comment by pascl** [comment]
Not tested with a lot of files, but the 1.4 version can support chd (and pbp and cue/bin)

I leave this issue open just in case.

**Comment by MessiahMozgus** [comment]
How do you get CHD to work with bleemsync or autobleem though?

**Comment by AnotherLife** [comment]
Enable the Retroarch emulator in the Bleemsync boot options.

**Comment by sesego** [comment]
theres a very simple script edit that will allow you to launch chd compressed games from the BleemSync launcher. I made a tut on reddit in the PSClassic sub. I also submitted a pull request to the BleemSync project to merge that change into the next version.

**Comment by MessiahMozgus** [comment]
It would be cool of we ever get to a point where the physical reset and disc buttons will still work with the RA emulation handoff though. I prefer autobleem above bleemsync and retroarch for the aesthetics. I'd just like the best compression with it.
