### ISSUE TITLE
Non-Psx games not working from ui

### ISSUE THREAD

**Issue by Damyos** [pascl/pbPSCReAlpha#29]
Just added a game using the option from the last version but after i select a game i got a black screen and then go back to the ui menu, i tested using retroarch directly and the roms starts fine.

This is the launch.sh created  

#!/bin/sh

echo 2 > /data/power/disable
mkdir -p "/tmp/ra_cache"
chmod +x /media/bleemsync/opt/retroarch/retroarch
HOME=/media/bleemsync/opt/retroarch /media/bleemsync/opt/retroarch/retroarch -L"/media/bleemsync/opt/retroarch/.config/retroarch/cores/snes9x_libretro.so" "/var/volatile/launchtmp/ff6.sfc" -v &> "/media/logs/retroarch.log"
rm -rf "tmp/ra_cache"
echo 0 > /data/power/disable

**Comment by pascl** [comment]
Is it the right name of your file ? The right extension ? The case-sensitivity ?

Is it the file in the same folder ? If yes, it should work. If not, edit the path /var/volatile/launchtmp/ to /media/yourPathFromUsbRoot/


For more information, after trying to launch, you can power off the PSC and check the retroarch.log file in /logs/ on your usb drive. (it is overwritten at each launch)

**Comment by Damyos** [comment]
The name file, extension are correct.

Just checked the log, this is it:


[INFO] RetroArch 1.7.8 (Git a6d84cb3cf)
[INFO] Redirecting save file to "/media/bleemsync/opt/retroarch/saves/ff6.srm".
[INFO] Redirecting savestate to "/media/bleemsync/opt/retroarch/savestates/ff6.state".
[INFO] === Build =======================================
[INFO] Capabilities: NEON VFPv3 VFPv4 
[INFO] Built: Sep  3 2019
[INFO] Version: 1.7.8
[INFO] Git: a6d84cb3cf
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/media/bleemsync/opt/retroarch/.config/retroarch/cores/snes9x_libretro.so"
sh: xz: command not found
[ERROR] Failed to open libretro core: "/media/bleemsync/opt/retroarch/.config/retroarch/cores/snes9x_libretro.so"
[ERROR] Error(s): /media/bleemsync/opt/retroarch/.config/retroarch/cores/snes9x_libretro.so: invalid ELF header
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

**Comment by pascl** [comment]
Ok it is the core which doesn't start directly.

The most probable issue (because it runs from retroarch) is that the latest cores have been compressed. Unzip them and you should have another single file without the .so. Move the compressed ones elsewhere and rename the uncompressed ones with .so extension.

**Comment by Damyos** [comment]
thats it!, now its working, thank you for your help.

**Comment by pascl** [comment]
fyi.
In order to have no need to uncompress a core, a file from the usb drive needs to be added internally.
Or maybe just do an overmount...

**Comment by sesego** [comment]
> fyi.
> In order to have no need to uncompress a core, a file from the usb drive needs to be added internally.
> Or maybe just doing an overmount would be enough...

which file?

**Comment by pascl** [comment]
🤔🤔
I have a notification, but I don't see any new comments...

Q: what file ?
A: the xz file in bleemsync/bin on your usb drive has to be copied to /usr/bin/ (need remount rw first)

**Comment by pascl** [comment]
Lines added by the 1.71 release are enough to launch compressed and uncompressed cores.
Use the button in the config tab to update your existing launch.sh files.
