### ISSUE TITLE
Quotes around values for Title or Discs causes a validation error

### ISSUE THREAD

**Issue by donpezet** [pascl/pbPSCReAlpha#3]
Many of my game images have spaces in their file names. I have noticed that if I use quote marks around their names that pbPSCReAlpha fails to match up the discs, CUE file and cover art. For example, a Game.ini like this will fail: 

`[Game]`
`Title="Medievil II"`
`Publisher=Sony`
`Year=2000`
`Players=1`
`Discs="Medievil II"`

Whereas a Game.ini like this will pass:

`[Game]`
`Title=Medievil II`
`Publisher=Sony`
`Year=2000`
`Players=1`
`Discs=Medievil II`

BleemSync uses quote marks in their sample configuration, so it would be nice if pbPSCReAlpha could support this as well. 

![image](https://user-images.githubusercontent.com/10239062/51081114-1abd8e00-16b6-11e9-943e-3ea37fb0f909.png)

**Comment by pascl** [comment]
It is ok with 0.61, quotes are discarded.
