### ISSUE TITLE
Retro Games In Folder Don't open

### ISSUE THREAD

**Issue by TwoTracks** [pascl/pbPSCReAlpha#34]
To start off I have just added Some roms onto bleemsync but after updating the software non of my games open. Did I do something wrong?

**Comment by pascl** [comment]
Can you copy your launch.sh for one of your non-working game ?

All games don't work ?
Only the last games you added ?
Only games using one (or more) core(s) ?

**Comment by TwoTracks** [comment]
Turns out it was s case sensitive directory. Took me a while but I figured it out. What a slap in the face haha

**Comment by TwoTracks** [comment]
Turns out it was s case sensitive directory. Took me a while but I figured it out. What a slap in the face haha
